name: CI

on: [push]

jobs:
  sast-scan:
    name: Run Bandit Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with: 
        python-version: 3.8

    - name: Install dependencies
      run: pip install bandit pyyaml

    - name: Run Bandit Scan
      run: bandit -ll -ii -r . -f json -o bandit-report.json

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: bandit-finding
        path: bandit-report.json

  image-scan:
    name: Built Image and Run Image Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Set Up Docker
        uses: docker/setup-docker-action@v4.1.0
        with:
          version: '20.10.7'

      - name: Docker Build Image
        runs: docker build -f Dockerfile -t myapp:latest .

      - name: Docker scan
        uses: docker/scout-action@v1.16.1
        with: 
          command: quickview, cves
          image: ${{ steps.meta.outputs.tags }}
          to-latest: true
          










      
