name: CI

on: [push]

jobs:
  sast-scan:
    name: Run Bandit Scan
    run-on: ubuntu-latest

  steps:
  - name: Checkout code
    uses: action/checkout@v2

  - name: Set up Python
    uses: action/setup-Python@v2
    with: 
      Python-version: 3.8

  - name: Install Bandit
    run: pip install Bandit

  - name: Run Bandit Scan
    run: bandit -r .
    
   
